apiVersion: v1
kind: Service
metadata:
    labels:
      app: sample-api
      type: restapi
    name: sample-api-service-loadbalancer
    namespace: gs7876
spec:
    type: LoadBalancer
    ports:
    - nodePort: 32766
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: sample-api
    sessionAffinity: None

# If you are using minikube the run "minikube tunnel". to get the external IP.
# https://minikube.sigs.k8s.io/docs/handbook/accessing/

