apiVersion: v1
kind: Service
metadata:
    labels:
      app: sample-api
      type: restapi
    name: sample-api-service-nodeport
    namespace: gs7876
spec:
    type: NodePort
    ports:
    - nodePort: 32331
      port: 9090
      targetPort: 9090
      protocol: TCP
    selector:
      app: sample-api
    sessionAffinity:


# minikube service sample-api-service-nodeport -n gs7876
# minikube service list
#Get the public IP address of one of your nodes that is running a Hello World pod. How you get this address depends on how you set up your cluster.
#For example, if you are using Minikube, you can see the node address by running kubectl cluster-info.
#If you are using Google Compute Engine instances, you can use the gcloud compute instances list command to see the public addresses of your nodes.

# https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/