apiVersion: v1
kind: Service
metadata:
    labels:
      app: sample-api
      type: restapi
    name: sample-api-service-clusterip
    namespace: gs7876
spec:
    type: ClusterIP
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: sample-api
    sessionAffinity: None

# https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
